$(document).ready(function(){
    $('.font-white').hover(
        function(){
            $(this).children('.en').stop().fadeIn();
            $(this).children('.zh').stop().fadeOut();
        },
        function(){
            $(this).children('.en').stop().fadeOut();
            $(this).children('.zh').stop().fadeIn();
        }
    );
    $('.menu-hover').hover(
        function(){
            $('.megamenu').stop().fadeIn();
        },
        function(){
            $('.megamenu').stop().fadeOut();
        }
    );
});
